### PR TITLE
Add systemd service file for daemon

### PR DESCRIPTION
**Pull request by aamcrae**
Added a systemd service file to allow daemon to be managed by systemd.

### CODE REVIEW

**Comment by sbf-** [comment]
Looks interesting but... this is for MySQL server installed or raspberry, right?
When I run this, it fails (SQLite installed)
```
pi@raspberrypi:~ $ sudo systemctl enable SBFspotUpload.service
Created symlink /etc/systemd/system/default.target.wants/SBFspotUpload.service → /etc/systemd/sys
tem/SBFspotUpload.service.
pi@raspberrypi:~ $ sudo systemctl status SBFspotUpload.service
● SBFspotUpload.service - SBFspot upload daemon
   Loaded: loaded (/etc/systemd/system/SBFspotUpload.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
pi@raspberrypi:~ $ sudo systemctl start SBFspotUpload.service
Failed to start SBFspotUpload.service: Unit mysql.service not found.
```

How can we make it work for MySQL server installed on another computer, and, more important: for SQLite?

**Comment by aamcrae** [comment]
It's hard to have a static file that covers all the possibilities, the easiest thing is to have the optional dependent services commented out, or perhaps the fail-safe option is to just depend on network.target.
Let me make that change.

**Comment by sbf-** [comment]
Well, the trick is to have 2 .service files for MySQL and SQLite and let `make` decide which one to copy.
We don't need an extra recipe `install_systemd` so the copy can be done inside `install_sqlite` and `install_mysql`

**Comment by aamcrae** [comment]
OK, I've added service files for mysql and mariadb, and added this into the standard install.

**Pull request merged**
