### PR TITLE
Enable Plantname for MQTT export

### PR DESCRIPTION
**Pull request by mincequi**
- Use retain flag for MQTT export
- Make MQTT a class
- Move some functions to appropriate places
- Some beautifications (convert to UNIX format)

I guess, this change is ok for master (instead of dev_v4).

### CODE REVIEW

**Comment by brevilo** [comment]
Please try to use atomic commits (or don't squash them) to facilitate change reviews. Thanks.

**Comment by brevilo** [comment]
Also, why introduce mixed indentation? Now [SPACEs and TABs are used](https://github.com/SBFspot/SBFspot/pull/434/files#diff-cee52afde59db3f806f2c6990e43799796800d5505fc23ac28cd215c610d3191R85) in the same line... Mistake or intentional choice?

**Comment by mincequi** [comment]
Ok, what is the issue with squashing?

I tried to not change the indention of the whole file to keep the the git history. Unfortunately, sbfspot heavily mixes styles. So, whenever I change something, I go for Unix line endings and spaces.

Currently, I am rewriting sbfspot and I also want to fix those kind of issues. However, it will be hard to trace back history then.

**Comment by brevilo** [comment]
> I am rewriting sbfspot and I also want to fix those kind of issues

Precisely :) While that's great, squashing the commits makes it really hard to distinguish the formatting changes from the functional changes or pure refactoring. Take the [config file](https://github.com/SBFspot/SBFspot/pull/434/files#diff-c1199e81e83fddb653c580c29c7de2ff7dfd17ef7f92c8f6bb5f7966cb5de905) as an example.

Thus I strongly recommend to *first* change the line breaks and/or fix indentation as pure whitepace changes. Only *then* should functional or refactoring changes be commit separately.

Makes sense?

**Comment by mincequi** [comment]
Ok, i see the point. So, splitting up PRs to _cosmetic_ and _functional_ changes makes it easier for reviewers to follow.
However, if I change a whole file due to new formatting all lines gets a new author while doing a "git blame" and one cannot easily trace back when and why a certain line of code was added.

So, your are saying that _comprehensible PRs/Commits_ are higher rated than _traceability of code history_?

**Comment by brevilo** [comment]
No, not "splitting up PRs", the commits in them.

> one cannot easily trace

To the contrary. Your changes will end up in the history no matter what, so for `git blame` purposes you still end up with your whitespace changes, until another commit will follow those up. *BUT* your functional changes will *follow* those, so the history/blaming won't be degraded in any way. It's rather the other way round: the atomic commits in the PR will obviously become part of the history, so their improved comprehensibility will also improve the history, i.e. your functional changes will be clearly visible since they're separated.

> comprehensible PRs/Commits are higher rated than traceability of code history

No, the former will lead to the latter as atomic commits are the foundation for traceability :)

**Comment by mincequi** [comment]
Ok, thanks for clarifying. I will respect that in upcoming PRs.

Then there is one aspect left:
if I change code in a file which is entirely in an old format (e.g. tabs instead spaces), would we result in a commit where **all** whitespaces of the **entire** file will be transformed into the new format?
What if i only change 100 lines out of 1000? Would it be legit to only reformat that portion where i was working on? Again a question of traceability :)

Thanks for your feedback! :)

**Comment by brevilo** [comment]
IMHO, *all* files should unix line breaks and *either* spaces *or* tabs. This should be defined for the whole project. What to use is @sbf-'s call to make, I think.

Should we decide on unix line breaks I recommend to simply use `dos2unix` before you start working on a file. Same for indentation: every decent editor can convert TABs and SPACEs. Just convert the and commit those whitespace changes only (saying so in the commit message), then start your work. This way the whole codebase should get converted over time.

Sounds good?

**Comment by mincequi** [comment]
Sounds good to me. 👍 

I am using QtCreator as IDE and changing format is a single mouse-click. So, if @sbf- agrees we can proceed that way. However, it became a little irrelevant for me, since i moved on to SBFspot v4 (using Qt).
As i believe, merging it back to the original master will be hard. I consider it as a complete replacement for the original SBFspot.
But, i will transform everything to unix line endings and SPACEs.

**Comment by brevilo** [comment]
"SBFspot v4"? I'm not aware of it. Is that a fork? And, yikes, Qt is dead :-p

**Comment by mincequi** [comment]
Yes, that's a fork.

Well, i wanted to extend SBFspot with a few features like: macOS support, daemon mode, better MQTT support and i discovered, that there is so much platform dependent code in it, that it is very hard to maintain.
Qt is the only framework that offers support for any platform with all the features we need: Ethernet, Bluetooth, SQL, MQTT, Json, daemon mode.
Furthermore: Qt is just awesome to code with 😛 
Boost does not support that high level of abstraction.

Another thing: yes, i am also coding a UI for SBFspot which is also done in Qt:
https://github.com/SBFspot/SBFspot/issues/245

Boy, give Qt a shot. No better framework out there ;)  (GUI or non-GUI)

**Comment by brevilo** [comment]
Son, I've worked with Qt for almost 20 years 😎 It's just sad to see how its parent company is run nowadays. But let's not get into that discussion here. Hope your fork takes off 👍

**Comment by sbf-** [comment]
Wow, a lot of activity here...

> Also, why introduce mixed indentation? Now SPACEs and TABs are used in the same line... Mistake or intentional choice?

This is caused by the use of different editors. I'm using Visual Studio on windows and I never change the TAB/SPACES setting (TAB size=4 and Keep TABs) - If that's really an issue, I can change it.

> IMHO, all files should use unix line breaks and either spaces or tabs.

Line breaks should be already LF (fixed in #395) - But again: different IDE, different behaviour. I guess in VS, new files will have CR/LF termination and existing files keep the line endings.

But what makes unix line breaks better? Because you're used to it as a linux guy? A decent editor doesn't care about line endings.

> Should we decide on unix line breaks I recommend to simply use `dos2unix` before you start working on a file

Hmm, only linux I guess? I'd rather look for a config setting...

**Comment by brevilo** [comment]
> But what makes unix line breaks better? Because you're used to it as a linux guy? 

Nope, Linux and macOS. Windows is the only outlier and can easily cause huge issues with git if committers haven't configured their Windows-git correctly (where it converts CRLF from/to LF on checkout/commit). Believe me, I've been there a number of times.

 > I'd rather look for a config setting

Sure, whatever does the job easiest for you. Linux and macOS users can use `dos2unix`, however, heck, even across the whole codebase they need to touch next :)

**Pull request merged**
