### PR TITLE
Fixes #3 - Add third inverter input

### LINKED ISSUE #3: Three string SMA inverters
Hi,

I just had a new SMA inverter installed yesterday that replaced three older units (the 17 year-old one had finally died).  I wanted better logging than the new inverter supports and came across this software.  Thanks so much, but it only grabs the data from the first two strings.

I've made the following changes, but seem to be missing something.  And I should add that the last time I worked in C or C++ regularly was 1994, so I am a little rusty.

In SBFspot.cpp

Around line 425:
   Was: "Inverters[inv]->calPdcTot = Inverters[inv]->Pdc1 + Inverters[inv]->Pdc2"
   Is:      "Inverters[inv]->calPdcTot = Inverters[inv]->Pdc1 + Inverters[inv]->Pdc2 + Inverters[inv]->Pdc3;"
   Added extra printf line for the String 3 information (copied from String 2 and modified)

Around line 2600:
  In "SpotDCPower" case
     Was: "last = 0x00251EFF;"
     Is:      "last = 0x004524FE;"
  In "SpotDCVoltage" case
     Was: "last = 0x004521FF;"
     Is:      "last = 0x004524FE;"
  I was just guessing that the data structures would be the same size and that seemed to work...

Around line 2900:
  In "DcMsWatt" case:
     Added a case for cls == 3
  In "DcMsVol" case:
     Added a case for cls == 3
  In "DcMsAmp" case:
     Added a case for cls == 3

I was just starting to work on the CSV and SQL sections, but feel like I am not following the flow of the code properly.

So, is there an easier way to go about this update?  I am glad to dig in or open up the firewall so you can address my inverter directly to help with the debugging the code against the new model.

Thanks

Randy

### PR DESCRIPTION
**Pull request by scotte**
For review... This all seems to be working, and I'm getting per-string data in pvoutput for all three strings (with change to vwPvoData).

Assume there are bugs and this is not yet correct! Also note that only sqlite3 has been tested. Mysql has not been tested!

SQL update scripts are called XXX as I don't know what the actual version would be.

Please provide any feedback or suggestions. Thanks!

### CODE REVIEW

**Comment by sbf-** [comment]
Thanks for the effort...
My biggest concern is the breaking changes for all the existing users due to the db schema change.

**Comment by scotte** [comment]
I totally understand that, but there's not really any easy way. I made a reasonable attempt at saving off the old table in the upgrade script, but as always with a change of this scope, there's an opportunity for something to break.

**Comment by Zwilla** [comment]
Hi @scotte can you add your pull request on my fork? Thx, Michael

**Comment by mr-russ** [comment]
I would like to understand the risks with the schema change.
It is only column additions, so if other db uses are coded well, there will be no impact. 

What are the specific risks we would like to avoid?

I don't quite yet understand how each string gets 0 rather than null in the db, so the additions for totals work properly.

**Comment by scotte** [comment]
@mr-russ It is a column addition, but not at the end of the table, hence it requires a DB migration as sbfspot uses positional SQL instead of declaring each column. There's definite risk, but in my opinion this is an important feature.

Let me also reply to @Zwilla - As for doing a pull in another fork - you can do this. Just add my fork as an additional remote and there's about a 1/2 dozen ways from there - you can cherry pick my commit, merge it in, or rebase your work. Whatever you want to do, but I leave that to you.

**Comment by sbf-** [comment]
Multi-string inverters are supported in V3.9.0

**Pull request closed without merging**
